// The readable side of the parity list, generated from its JSON: Parity/README.md (one row per feature with its
// status, scenario, last match and memory) and Parity/Scenarios*.md (the steps of every scenario and what each
// feature lacks). Pages stay within 120 columns and 300 lines like every file of swiftui/.

import Foundation

public enum ParitySummary {
    public static let width = 118
    public static let pageLines = 280

    /// File name and text of every generated page.
    public static func pages(_ list: ParityList, results: ParityResults) -> [(name: String, text: String)] {
        var pages = [(name: "README.md", text: readme(list, results: results))]
        for (index, page) in paginate(scenarioLines(list, results: results)).enumerated() {
            pages.append((name: index == 0 ? "Scenarios.md" : "Scenarios-\(index + 1).md", text: page))
        }
        return pages
    }

    static func readme(_ list: ParityList, results: ParityResults) -> String {
        let counts = NativeStatus.allCases.map { status in
            "\(list.features.filter { $0.native == status }.count) \(status.rawValue)"
        }
        let runnable = list.scenarios.filter(\.runnable).count
        let measured = results.scenarios.values.flatMap(\.values)
        let versions = Set(measured.compactMap(\.currentVersion)).sorted().joined(separator: ", ")
        let dates = Set(measured.map(\.date)).sorted()
        var lines = [
            "# Native parity list",
            "",
        ]
        lines += wrap(
            "Every feature of the current app (docs/wiki/features.json), the scenario that shows it in both apps, "
                + "and how far the native app has come. Generated by `gm-measure parity summary` from "
                + "features-*.json, scenarios-*.json and results.json: edit those, then run it. "
                + "`gm-measure parity --record` measures every scenario the native app can show and updates "
                + "results.json. The steps of each scenario and what each feature lacks are in "
                + "[Scenarios.md](Scenarios.md) and the pages after it."
        )
        lines.append("")
        lines += wrap(
            "Native status: done looks and works like the current app; partial has some of it (most often the look, "
                + "not every action); missing is not in the native app yet."
        )
        lines.append("")
        lines += wrap(
            "Native: \(counts.joined(separator: ", ")) (\(list.features.count) features). "
                + "\(runnable) of \(list.scenarios.count) scenarios run in both apps."
        )
        if let last = dates.last {
            lines.append("")
            lines += wrap(
                "Last measured \(last) against the current app \(versions.isEmpty ? "?" : versions). Match is the "
                    + "share of identical pixels below the title bar, light / dark; memory is the average while the "
                    + "scenario is on screen in light mode, current app / native app."
            )
        }
        lines += [
            "",
            "| Feature | Id | Native | Scenario | Match light / dark | Memory current / native |",
            "|---|---|---|---|---|---|",
        ]
        for feature in list.features {
            let light = results.measurement(feature.scenario, "light")
            let dark = results.measurement(feature.scenario, "dark")
            let match = light == nil && dark == nil
                ? "-"
                : "\(ParityFormat.percent(light?.contentPercent)) / \(ParityFormat.percent(dark?.contentPercent))"
            let memoryFrom = light ?? dark
            let memory = memoryFrom.map {
                "\(ParityFormat.megabytes($0.currentMb)) / \(ParityFormat.megabytes($0.nativeMb))"
            } ?? "-"
            lines.append(
                "| \(feature.name) | \(feature.id) | \(feature.native.rawValue) | \(feature.scenario) | \(match) "
                    + "| \(memory) |"
            )
        }
        return lines.joined(separator: "\n") + "\n"
    }

    static func scenarioLines(_ list: ParityList, results: ParityResults) -> [String] {
        var lines = ["# Parity scenarios", ""]
        lines += wrap(
            "How to reach each screen, the same way in both apps, on the docs demo (scripts/make-docs-demo.sh). "
                + "Generated by `gm-measure parity summary` from scenarios-*.json and features-*.json. A scenario "
                + "with a run spec is driven by `gm-measure parity`; the others wait for the native app."
        )
        for scenario in list.scenarios {
            let state = scenario.runnable ? "runs in both apps" : "native app cannot show it yet"
            lines += ["", "## \(scenario.id): \(scenario.title) (\(state))", ""]
            lines += wrap("Folder: " + (scenario.folder.map { "demo `\($0)`" } ?? "none"))
            lines.append("")
            for (index, step) in scenario.steps.enumerated() {
                lines += wrap("\(index + 1). \(step)", hanging: "   ")
            }
            if let note = scenario.note, !note.isEmpty {
                lines.append("")
                lines += wrap("Note: " + note.joined(separator: " "))
            }
            let measured = ["light", "dark"].compactMap { mode in
                results.measurement(scenario.id, mode).map { measurement in
                    "\(mode) \(ParityFormat.percent(measurement.contentPercent)) ("
                        + "\(ParityFormat.megabytes(measurement.currentMb)) / "
                        + "\(ParityFormat.megabytes(measurement.nativeMb)), \(measurement.date))"
                }
            }
            if !measured.isEmpty {
                lines.append("")
                lines += wrap("Measured: " + measured.joined(separator: ", ") + ".")
            }
            lines.append("")
            for feature in list.features(in: scenario.id) {
                let gaps = feature.gapText.map { " Native lacks: \($0)." } ?? ""
                lines += wrap(
                    "- \(feature.name) (`\(feature.id)`, \(feature.native.rawValue)): \(feature.check).\(gaps)",
                    hanging: "  "
                )
            }
        }
        return lines
    }

    /// Splits at "## " headings so each page stays under `pageLines`; later pages get a title line.
    public static func paginate(_ lines: [String]) -> [String] {
        var pages: [[String]] = [[]]
        var section: [String] = []
        func flush() {
            if pages[pages.count - 1].count + section.count > pageLines && !pages[pages.count - 1].isEmpty {
                pages.append(["# Parity scenarios (continued)"])
            }
            pages[pages.count - 1] += section
            section = []
        }
        for line in lines {
            if line.hasPrefix("## ") {
                // The blank line before a heading belongs to the new section.
                if section.last == "" {
                    section.removeLast()
                    flush()
                    section = [""]
                } else {
                    flush()
                }
            }
            section.append(line)
        }
        flush()
        return pages.map { $0.joined(separator: "\n") + "\n" }
    }

    /// Breaks `text` into lines of at most `width` columns at spaces; later lines start with `hanging`.
    public static func wrap(_ text: String, width: Int = width, hanging: String = "") -> [String] {
        var lines: [String] = []
        var current = ""
        for word in text.split(separator: " ", omittingEmptySubsequences: true) {
            if current.isEmpty {
                current = String(word)
            } else if current.count + 1 + word.count <= width {
                current += " " + word
            } else {
                lines.append(current)
                current = hanging + word
            }
        }
        if !current.isEmpty || lines.isEmpty {
            lines.append(current)
        }
        return lines
    }
}
