// The color tokens every theme sets, in src/app.css order. Fonts, sizes and
// the corner radius are not colors and stay in app.css.

export const COLOR_TOKENS = [
  "--bg",
  "--frame",
  "--panel",
  "--panel-alt",
  "--border",
  "--border-strong",
  "--text",
  "--text-dim",
  "--text-faint",
  "--accent",
  "--accent-hover",
  "--accent-text",
  "--hover",
  "--selected",
  "--selected-inactive",
  "--danger",
  "--success",
  "--warning",
  "--shadow",
  "--overlay",
  "--editor-bg",
  "--editor-gutter",
  "--editor-line-number",
  "--editor-active-line",
  "--editor-selection",
  "--editor-cursor",
  "--term-background",
  "--term-foreground",
  "--term-cursor",
  "--term-selection",
  "--term-black",
  "--term-red",
  "--term-green",
  "--term-yellow",
  "--term-blue",
  "--term-magenta",
  "--term-cyan",
  "--term-white",
  "--term-bright-black",
  "--term-bright-red",
  "--term-bright-green",
  "--term-bright-yellow",
  "--term-bright-blue",
  "--term-bright-magenta",
  "--term-bright-cyan",
  "--term-bright-white",
  "--term-scrollbar",
  "--term-scrollbar-hover",
  "--diff-modified",
  "--diff-modified-edge",
  "--diff-added",
  "--diff-added-edge",
  "--diff-deleted",
  "--diff-deleted-edge",
  "--diff-conflict",
  "--diff-conflict-edge",
  "--diff-inline",
  "--tok-keyword",
  "--tok-string",
  "--tok-number",
  "--tok-comment",
  "--tok-type",
  "--tok-function",
  "--tok-property",
  "--tok-meta",
  "--tok-tag",
  "--tok-attr",
  "--tok-invalid",
  "--bracket-1",
  "--bracket-2",
  "--bracket-3",
] as const;

export type ColorToken = (typeof COLOR_TOKENS)[number];

/** A full set of token values for one theme. */
export type ThemeColors = Record<ColorToken, string>;
