// gm-measure commands: writes Sources/GitManagerNative/Generated/PaletteCommands*.swift, the Command Palette's
// commands as the current app's registry lists them (swiftui/Palette/export.ts, run with Bun like `tokens`), so
// titles, categories, shortcuts and their state are never typed by hand. --check fails (exit 1) when the files are
// out of date.

import Foundation
import MeasureKit

enum Commands {
    struct Command: Decodable {
        let id: String
        let title: String
        let category: String
        let shortcut: String?
        let enabled: Bool
        let reason: String?
        let checkedLight: Bool?
        let checkedDark: Bool?
        let order: Int
    }

    static let perFile = 45

    static func run(_ arguments: [String]) throws -> Int32 {
        var arguments = arguments
        let check = arguments.contains("--check")
        arguments.removeAll { $0 == "--check" }
        guard arguments.isEmpty else {
            print(usage)
            return 2
        }
        let result = try AppLauncher.run(
            "/usr/bin/env",
            ["bun", "--tsconfig-override", "swiftui/Palette/tsconfig.json", "swiftui/Palette/export.ts"],
            in: repoRoot
        )
        guard result.status == 0, let json = result.output.split(separator: "\n").first(where: { $0.hasPrefix("[") })
        else {
            throw ToolError("The palette export failed:\n\(result.output)")
        }
        let commands = try JSONDecoder().decode([Command].self, from: Data(json.utf8))
        let wanted = files(commands)
        let existing = (try? FileManager.default.contentsOfDirectory(atPath: Tokens.generatedDir)) ?? []
        let stale = existing.filter { $0.hasPrefix("PaletteCommands") && wanted[$0] == nil }
        let changed = wanted.filter { name, source in
            (try? String(contentsOfFile: path(name), encoding: .utf8)) != source
        }
        if check {
            if changed.isEmpty && stale.isEmpty {
                print("Generated palette commands are up to date (\(commands.count) commands).")
                return 0
            }
            print("Generated palette commands are out of date: run `swift run gm-measure commands` in swiftui/.")
            return 1
        }
        for name in stale {
            try FileManager.default.removeItem(atPath: path(name))
        }
        for (name, source) in changed {
            try source.write(toFile: path(name), atomically: true, encoding: .utf8)
        }
        print("Wrote \(commands.count) palette commands: \(changed.count) files changed, \(stale.count) removed.")
        return 0
    }

    private static func path(_ name: String) -> String {
        (Tokens.generatedDir as NSString).appendingPathComponent(name)
    }

    /// PaletteCommands.swift (the list) and PaletteCommands<N>.swift (the commands, `perFile` each).
    static func files(_ commands: [Command]) -> [String: String] {
        let header = "// Generated by `gm-measure commands` from swiftui/Palette/export.ts. Do not edit.\n\n"
        var result: [String: String] = [:]
        let chunks = stride(from: 0, to: commands.count, by: perFile).map {
            Array(commands[$0..<min(commands.count, $0 + perFile)])
        }
        var parts: [String] = []
        for (index, chunk) in chunks.enumerated() {
            let name = "part\(index + 1)"
            parts.append(name)
            var lines = [header + "import NativeCore\n", "extension PaletteCommands {",
                         "    static func \(name)(dark: Bool) -> [PaletteCommand] {", "        ["]
            for command in chunk {
                lines += entry(command).map { "            " + $0 }
            }
            lines += ["        ]", "    }", "}", ""]
            result["PaletteCommands\(index + 1).swift"] = lines.joined(separator: "\n")
        }
        let list = parts.map { "\($0)(dark: dark)" }.joined(separator: " + ")
        result["PaletteCommands.swift"] = header + """
            import NativeCore

            /// Every command the Command Palette lists, in its order without a query (\(commands.count) commands).
            enum PaletteCommands {
                static func all(dark: Bool) -> [PaletteCommand] {
                    \(list)
                }
            }

            """
        return result
    }

    private static func entry(_ command: Command) -> [String] {
        let checked: String
        if command.checkedLight == command.checkedDark {
            checked = literal(command.checkedLight)
        } else {
            checked = "dark ? \(literal(command.checkedDark)) : \(literal(command.checkedLight))"
        }
        return [
            "PaletteCommand(",
            "    id: \(quoted(command.id)), title: \(quoted(command.title)),",
            "    category: \(quoted(command.category)), shortcut: \(quoted(command.shortcut)),",
            "    enabled: \(command.enabled), checked: \(checked), reason: \(quoted(command.reason)),",
            "    order: \(command.order)",
            "),",
        ]
    }

    private static func literal(_ value: Bool?) -> String {
        value.map { "\($0)" } ?? "nil"
    }

    private static func quoted(_ text: String?) -> String {
        guard let text else {
            return "nil"
        }
        let escaped = text.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
