// gm-measure icons: writes Sources/GitManagerNative/Generated/Icons*.swift, the current app's stroke icons
// (src/lib/ui/icons.ts:
// SVG paths on a 24-point grid) as plain text, so the native app draws the very same shapes. Like `tokens`, it
// runs the TypeScript with Bun. --check fails (exit 1) when the files are out of date; CI runs it.

import Foundation
import MeasureKit

enum Icons {
    static let generatedDir = (swiftuiDir as NSString).appendingPathComponent("Sources/GitManagerNative/Generated")
    /// Lines per generated file, under the 300-line standard with room for the header.
    static let chunkLines = 270

    private static let exportScript = """
        import { icons } from "./src/lib/ui/icons.ts";
        console.log(JSON.stringify(icons));
        """

    static func run(_ arguments: [String]) throws -> Int32 {
        var arguments = arguments
        let check = arguments.contains("--check")
        arguments.removeAll { $0 == "--check" }
        guard arguments.isEmpty else {
            print(usage)
            return 2
        }
        let result = try AppLauncher.run("/usr/bin/env", ["bun", "--eval", exportScript], in: repoRoot)
        guard result.status == 0, let json = result.output.split(separator: "\n").last.map(String.init),
              let icons = try JSONSerialization.jsonObject(with: Data(json.utf8)) as? [String: [String]] else {
            throw ToolError("The icon export failed:\n\(result.output)")
        }
        let files = IconsRender.files(icons)
        let existing = (try? FileManager.default.contentsOfDirectory(atPath: generatedDir)) ?? []
        let stale = existing.filter { $0.hasPrefix("Icons") && $0.hasSuffix(".swift") && files[$0] == nil }
        let changed = files.filter { name, source in
            (try? String(contentsOfFile: path(name), encoding: .utf8)) != source
        }
        if check {
            if changed.isEmpty && stale.isEmpty {
                print("Generated icons are up to date (\(icons.count) icons).")
                return 0
            }
            print("Generated icons are out of date: run `swift run gm-measure icons` in swiftui/.")
            return 1
        }
        for name in stale {
            try FileManager.default.removeItem(atPath: path(name))
        }
        for (name, source) in changed {
            try source.write(toFile: path(name), atomically: true, encoding: .utf8)
        }
        print("Wrote \(generatedDir): \(changed.count) icon files changed, \(stale.count) removed.")
        print("\(icons.count) icons.")
        return 0
    }

    private static func path(_ name: String) -> String {
        (generatedDir as NSString).appendingPathComponent(name)
    }
}

enum IconsRender {
    private static let header = [
        "// Generated by `swift run gm-measure icons` from src/lib/ui/icons.ts. Do not edit: change the icons there",
        "// and run the tool again. CI checks these files are up to date.",
    ]

    /// File name to contents: IconsData1.swift... with the icons as text, and Icons.swift with the lookup.
    static func files(_ icons: [String: [String]]) -> [String: String] {
        var chunks: [[String]] = [[]]
        for name in icons.keys.sorted() {
            var block = [name]
            for path in icons[name] ?? [] {
                block += wrap(path)
            }
            block.append("")
            if (chunks.last?.count ?? 0) + block.count > Icons.chunkLines {
                chunks.append([])
            }
            chunks[chunks.count - 1] += block
        }
        var files: [String: String] = [:]
        for (index, chunk) in chunks.enumerated() {
            let body = chunk.map { $0.isEmpty ? "" : "        \($0)" }
            let lines = header + ["", "extension Icons {", "    static let data\(index + 1) = \"\"\""]
                + body + ["        \"\"\"", "}", ""]
            files["IconsData\(index + 1).swift"] = lines.joined(separator: "\n")
        }
        files["Icons.swift"] = indexFile(chunkCount: chunks.count)
        return files
    }

    /// A long path split over lines ending in `\`, which Swift joins back without a line break.
    private static func wrap(_ path: String, width: Int = 100) -> [String] {
        var lines: [String] = []
        var rest = Substring(path)
        while rest.count > width {
            let cut = rest.index(rest.startIndex, offsetBy: width)
            lines.append(String(rest[..<cut]) + "\\")
            rest = rest[cut...]
        }
        lines.append(String(rest))
        return lines
    }

    private static func indexFile(chunkCount: Int) -> String {
        let chunks = (1...chunkCount).map { "data\($0)" }.joined(separator: ", ")
        return (header + [
            "",
            "/// The current app's stroke icons: name to SVG paths on a 24-point grid, drawn by Icon.swift.",
            "enum Icons {",
            "    static let paths: [String: [String]] = parse([\(chunks)])",
            "",
            "    /// Each icon is its name, then one path per line, then a blank line.",
            "    private static func parse(_ chunks: [String]) -> [String: [String]] {",
            "        var icons: [String: [String]] = [:]",
            "        for block in chunks.joined(separator: \"\\n\").components(separatedBy: \"\\n\\n\") {",
            "            let lines = block.split(separator: \"\\n\").map(String.init)",
            "            if let name = lines.first {",
            "                icons[name] = Array(lines.dropFirst())",
            "            }",
            "        }",
            "        return icons",
            "    }",
            "}",
            "",
        ]).joined(separator: "\n")
    }
}
