// The Swift files gm-measure tokens writes: Generated/Themes.swift (the types, the token names and the list
// of themes) and Generated/Themes/<id>.swift (one theme as JSON, one token per line). JSON in strings, not
// Swift literals: 42 dictionary literals took the Swift optimizer over ten minutes; strings cost nothing.

import Foundation
import MeasureKit

enum TokensRender {
    private static let header = [
        "// Generated by `swift run gm-measure tokens` from src/lib/themes (catalog.ts, themeIndex.ts, tokens.ts).",
        "// Do not edit: change the themes there and run the tool again. CI checks these files are up to date.",
    ]

    /// Path relative to Generated/ to file contents.
    static func files(_ export: Tokens.Export) throws -> [String: String] {
        var files: [String: String] = [:]
        for theme in export.themes {
            files["Themes/\(theme.id).swift"] = try themeFile(theme, tokens: export.tokens)
        }
        files["Themes.swift"] = indexFile(export)
        return files
    }

    /// "monokai-pro" becomes "monokaiPro".
    static func identifier(_ themeID: String) -> String {
        let words = themeID.split(whereSeparator: { !$0.isLetter && !$0.isNumber }).map(String.init)
        guard let first = words.first else {
            return "theme"
        }
        return first.lowercased() + words.dropFirst().map { $0.prefix(1).uppercased() + $0.dropFirst() }.joined()
    }

    private static func themeFile(_ theme: Tokens.Export.Theme, tokens: [String]) throws -> String {
        guard let colors = theme.colors else {
            throw ToolError("Theme \(theme.id) has no colors")
        }
        guard ["light", "dark", "high-contrast-light", "high-contrast-dark"].contains(theme.kind) else {
            throw ToolError("Theme \(theme.id) has an unknown kind \(theme.kind)")
        }
        var lines = header + ["", "extension Themes {", "    static let \(identifier(theme.id))JSON = ##\"\"\""]
        lines.append("    {")
        lines.append("      \(try jsonText("id")): \(try jsonText(theme.id)),")
        lines.append("      \(try jsonText("name")): \(try jsonText(theme.name)),")
        lines.append("      \(try jsonText("kind")): \(try jsonText(theme.kind)),")
        lines.append("      \(try jsonText("colors")): {")
        for (index, token) in tokens.enumerated() {
            guard let value = colors[token] else {
                throw ToolError("Theme \(theme.id) has no \(token)")
            }
            let comma = index == tokens.count - 1 ? "" : ","
            lines.append("        \(try jsonText(token)): \(try jsonText(value))\(comma)")
        }
        lines += ["      }", "    }", "    \"\"\"##", "}", ""]
        return lines.joined(separator: "\n")
    }

    private static func indexFile(_ export: Tokens.Export) -> String {
        var lines = header + [
            "",
            "import Foundation",
            "",
            "enum ThemeKind: String, Decodable {",
            "    case light",
            "    case dark",
            "    case highContrastLight = \"high-contrast-light\"",
            "    case highContrastDark = \"high-contrast-dark\"",
            "}",
            "",
            "struct ThemeTokens: Decodable {",
            "    let id: String",
            "    let name: String",
            "    let kind: ThemeKind",
            "    /// CSS token name (\"--bg\") to its value: #rrggbb, or rgba(...) for translucent tokens and shadows.",
            "    let colors: [String: String]",
            "}",
            "",
            "enum Themes {",
            "    /// Every token name, in src/app.css order.",
            "    static let tokenNames: [String] = [",
        ]
        lines += export.tokens.map { "        \"\($0)\"," }
        lines += [
            "    ]",
            "",
            "    /// Every theme, in the current app's order; decoded once, on first use.",
            "    static let all: [ThemeTokens] = [",
        ]
        lines += export.themes.map { "        \(identifier($0.id))JSON," }
        lines += [
            "    ].map(decode)",
            "",
            "    /// The data comes from the tool, so it always decodes.",
            "    private static func decode(_ json: String) -> ThemeTokens {",
            "        do {",
            "            return try JSONDecoder().decode(ThemeTokens.self, from: Data(json.utf8))",
            "        } catch {",
            "            fatalError(\"Generated theme does not decode: \\(error)\")",
            "        }",
            "    }",
            "}",
            "",
        ]
        return lines.joined(separator: "\n")
    }

    private static func jsonText(_ text: String) throws -> String {
        let options: JSONSerialization.WritingOptions = [.fragmentsAllowed, .withoutEscapingSlashes]
        let data = try JSONSerialization.data(withJSONObject: text, options: options)
        return String(decoding: data, as: UTF8.self)
    }
}
