// Every action of the native menu bar, shared by the menu definition (menuSpec.ts), its
// enabled and checked state (menuState.ts), the dispatcher (menuActions.ts) and the tests.

export const MENU_ACTIONS = [
  "app.about",
  "app.checkForUpdates",
  "app.settings",
  "file.newWindow",
  "file.openFolder",
  "file.openFolderNewWindow",
  "file.openWorkspace",
  "file.clearRecent",
  "file.addFolder",
  "file.saveWorkspace",
  "file.save",
  "file.saveAll",
  "file.revert",
  "file.compareWithClipboard",
  "file.compareWith",
  "file.localHistory",
  "file.recentlyDeleted",
  "file.closeTab",
  "file.reopenClosedTab",
  "file.closeFolder",
  "file.closeWindow",
  "edit.undo",
  "edit.redo",
  "edit.delete",
  "edit.selectAll",
  "edit.find",
  "edit.replace",
  "edit.findNext",
  "edit.findPrevious",
  "edit.selectAllOccurrences",
  "edit.findInFiles",
  "edit.replaceInFiles",
  "edit.goToFile",
  "edit.recentFiles",
  "edit.goToClass",
  "edit.goToSymbol",
  "edit.searchEverywhere",
  "view.commandPalette",
  "view.changes",
  "view.branches",
  "view.scripts",
  "view.log",
  "view.filesPanel",
  "view.sidebar",
  "view.leftActivityBar",
  "view.rightActivityBar",
  "view.terminal",
  "view.gitConsole",
  "view.wordWrap",
  "view.stickyScroll",
  "view.minimap",
  "view.fileIconsOff",
  "view.fileIconsMinimal",
  "view.fileIconsMaterial",
  "view.detectIndentation",
  "view.notifications",
  "view.doNotDisturb",
  "view.markdownEditor",
  "view.markdownSplit",
  "view.markdownPreview",
  "view.themeLight",
  "view.themeDark",
  "view.themeSystem",
  "view.zoomIn",
  "view.zoomOut",
  "view.zoomReset",
  "code.lineComment",
  "code.blockComment",
  "code.duplicate",
  "code.deleteLine",
  "code.joinLines",
  "code.moveLineUp",
  "code.moveLineDown",
  "code.indent",
  "code.unindent",
  "code.toggleCase",
  "code.sortLines",
  "code.expand",
  "code.collapse",
  "code.expandAll",
  "code.collapseAll",
  "code.goToLine",
  "code.selectNextOccurrence",
  "git.commit",
  "git.push",
  "git.updateProject",
  "git.pull",
  "git.fetchCurrent",
  "git.fetch",
  "git.merge",
  "git.rebase",
  "git.interactiveRebase",
  "git.branches",
  "git.newBranch",
  "git.newTag",
  "git.resetHead",
  "git.undoLast",
  "git.resolveConflicts",
  "git.continueOp",
  "git.abortOp",
  "git.skipCommit",
  "git.showLog",
  "git.showConsole",
  "git.showReflog",
  "git.bisect.start",
  "git.bisect.good",
  "git.bisect.bad",
  "git.bisect.skip",
  "git.bisect.reset",
  "git.patch.create",
  "git.patch.createFromCommit",
  "git.patch.apply",
  "git.patch.applyClipboard",
  "git.stash",
  "git.unstash",
  "git.shelve",
  "git.showShelf",
  "git.rollback",
  "git.showLocalChanges",
  "git.lines.stage",
  "git.lines.unstage",
  "git.lines.discard",
  "git.file.commit",
  "git.file.add",
  "git.file.annotate",
  "git.file.showDiff",
  "git.file.compareRevision",
  "git.file.compareBranch",
  "git.file.history",
  "git.file.historySelection",
  "git.file.rollback",
  "git.worktree.new",
  "git.worktree.show",
  "git.worktree.prune",
  "git.submodule.init",
  "git.submodule.update",
  "git.submodule.updateRemote",
  "git.submodule.sync",
  "git.submodule.add",
  "git.submodule.remove",
  "git.submodule.open",
  "git.lfs.track",
  "git.lfs.untrack",
  "git.lfs.pull",
  "git.lfs.fetch",
  "git.lfs.prune",
  "git.lfs.install",
  "git.manageRemotes",
  "git.openRemote",
  "git.clone",
  "git.github.open",
  "git.github.createPullRequest",
  "git.github.pullRequests",
  "git.github.copyLink",
  "git.github.share",
  "git.github.syncFork",
  "git.github.createGist",
  "git.cherryPick",
  "git.forcePush",
  "window.nextTab",
  "window.previousTab",
  "window.pinTab",
  "window.splitRight",
  "window.moveTabToOtherGroup",
  "window.focusLeftGroup",
  "window.focusRightGroup",
  "window.closeGroup",
  "help.docs",
  "help.shortcuts",
  "help.whatsNew",
  "help.releaseNotes",
  "help.mcpTools",
  "help.reportBug",
  "help.requestFeature",
  "help.star",
] as const;

export type MenuAction = (typeof MENU_ACTIONS)[number];

/** Actions that run on the focused CodeMirror editor (editorCommands.ts). */
export const EDITOR_ACTIONS = [
  "edit.find",
  "edit.replace",
  "edit.findNext",
  "edit.findPrevious",
  "edit.selectAllOccurrences",
  "code.lineComment",
  "code.blockComment",
  "code.duplicate",
  "code.deleteLine",
  "code.joinLines",
  "code.moveLineUp",
  "code.moveLineDown",
  "code.indent",
  "code.unindent",
  "code.toggleCase",
  "code.sortLines",
  "code.expand",
  "code.collapse",
  "code.expandAll",
  "code.collapseAll",
  "code.goToLine",
  "code.selectNextOccurrence",
] as const satisfies readonly MenuAction[];

export type EditorAction = (typeof EDITOR_ACTIONS)[number];

export function isEditorAction(action: MenuAction): action is EditorAction {
  return (EDITOR_ACTIONS as readonly MenuAction[]).includes(action);
}

/** The platform the menu is built for: macOS has the app menu, the others put its items in File and Help. */
export type MenuPlatform = "macos" | "windows" | "linux";

/** The main window, or the reduced window git opens as its mergetool. */
export type MenuMode = "app" | "mergeTool";
