// gm-measure tokens: writes App/Sources/Generated/Themes.swift, every theme's 73 color tokens exactly as
// the current app computes them (src/lib/themes/catalog.ts), so SwiftUI colors are never typed by hand.
// The catalog is TypeScript, so this runs it with Bun, the way the tool runs git and open.
// --check fails (exit 1) when the file is out of date; CI runs it.

import Foundation
import MeasureKit

enum Tokens {
    static let outputPath = (swiftuiDir as NSString).appendingPathComponent("App/Sources/Generated/Themes.swift")

    /// Prints every theme with its kind and colors as JSON.
    private static let exportScript = """
        import { THEME_INDEX } from "./src/lib/themes/themeIndex.ts";
        import { themeColors } from "./src/lib/themes/catalog.ts";
        import { COLOR_TOKENS } from "./src/lib/themes/tokens.ts";
        console.log(JSON.stringify({ tokens: COLOR_TOKENS, themes: THEME_INDEX.map((theme) => ({ ...theme, colors: themeColors(theme.id) })) }));
        """

    private struct Export: Decodable {
        struct Theme: Decodable {
            let id: String
            let name: String
            let kind: String
            let colors: [String: String]?
        }

        let tokens: [String]
        let themes: [Theme]
    }

    static func run(_ arguments: [String]) throws -> Int32 {
        var arguments = arguments
        let check = arguments.contains("--check")
        arguments.removeAll { $0 == "--check" }
        guard arguments.isEmpty else {
            print(usage)
            return 2
        }
        let result = try AppLauncher.run("/usr/bin/env", ["bun", "--eval", exportScript], in: repoRoot)
        guard result.status == 0, let json = result.output.split(separator: "\n").last.map(String.init) else {
            throw ToolError("The theme export failed:\n\(result.output)")
        }
        let export = try JSONDecoder().decode(Export.self, from: Data(json.utf8))
        let source = try render(export)
        let existing = try? String(contentsOfFile: outputPath, encoding: .utf8)
        if check {
            if existing == source {
                print("Themes.swift is up to date (\(export.themes.count) themes, \(export.tokens.count) tokens).")
                return 0
            }
            print("Themes.swift is out of date: run `swift run gm-measure tokens` in swiftui/ and commit it.")
            return 1
        }
        try FileManager.default.createDirectory(atPath: (outputPath as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
        try source.write(toFile: outputPath, atomically: true, encoding: .utf8)
        print("Wrote \(outputPath) (\(export.themes.count) themes, \(export.tokens.count) tokens).")
        return 0
    }

    private static func render(_ export: Export) throws -> String {
        var lines = [
            "// Generated by `swift run gm-measure tokens` from src/lib/themes (catalog.ts, themeIndex.ts, tokens.ts).",
            "// Do not edit: change the themes there and run the tool again. CI checks this file is up to date.",
            "",
            "enum ThemeKind: String {",
            "    case light",
            "    case dark",
            "    case highContrastLight = \"high-contrast-light\"",
            "    case highContrastDark = \"high-contrast-dark\"",
            "}",
            "",
            "struct ThemeTokens {",
            "    let id: String",
            "    let name: String",
            "    let kind: ThemeKind",
            "    /// CSS token name (\"--bg\") to its value: #rrggbb, or rgba(...) for translucent tokens and shadows.",
            "    let colors: [String: String]",
            "}",
            "",
            "enum Themes {",
            "    /// Every token name, in src/app.css order.",
            "    static let tokenNames: [String] = [",
        ]
        lines.append(contentsOf: export.tokens.map { "        \(literal($0))," })
        lines.append(contentsOf: ["    ]", "", "    static let all: [ThemeTokens] = ["])
        for theme in export.themes {
            guard let colors = theme.colors else {
                throw ToolError("Theme \(theme.id) has no colors")
            }
            guard let kind = ["light": ".light", "dark": ".dark", "high-contrast-light": ".highContrastLight", "high-contrast-dark": ".highContrastDark"][theme.kind] else {
                throw ToolError("Theme \(theme.id) has an unknown kind \(theme.kind)")
            }
            lines.append("        ThemeTokens(id: \(literal(theme.id)), name: \(literal(theme.name)), kind: \(kind), colors: [")
            for token in export.tokens {
                guard let value = colors[token] else {
                    throw ToolError("Theme \(theme.id) has no \(token)")
                }
                lines.append("            \(literal(token)): \(literal(value)),")
            }
            lines.append("        ]),")
        }
        lines.append(contentsOf: ["    ]", "}", ""])
        return lines.joined(separator: "\n")
    }

    private static func literal(_ text: String) -> String {
        "\"" + text.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"") + "\""
    }
}
